### Reading Data From Different Sources

In [1]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))

In [2]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [6]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [7]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [8]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [8]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [11]:
df.to_csv("wine.csv")

In [10]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ----- ---------------------------------- 0.5/4.0 MB 124.3 kB/s eta 0:00:28
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ------- -------------------------------- 0.8/4.0 MB 137.5 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ---------- ----------------------------- 1.0/4.0 MB 124.6 kB/s eta 0:00:24
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   ------------- -------------------------- 1.3/4.0 MB 119.6 kB/s eta 0:00:23
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   --------------- ------------------------ 1.6/4.0 MB 126.0 kB/s eta 0:00:20
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   ------------------ --------------------- 1.8/4.0 MB 122.9 kB/s eta 0:00:18
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 126.1 kB/s eta 0:00:16
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 126.1 kB/s eta 0:00:13
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   -------------------------- ------------- 2.6/4.0 MB 127.2 kB/s eta 0:00:11
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 126.5 kB/s eta 0:00:09
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 129.5 kB/s eta 0:00:07
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ---------------------------------- ----- 3.4/4.0 MB 133.7 kB/s eta 0:00:05
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 135.6 kB/s eta 0:00:03
   ---------------------------------------  3.9/4.0 MB 134.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 134.8 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 134.8 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.0

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
!pip install html5lib
!pip install beautifulsoup4

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in d:\dev\.venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-1.1 webencodings-0.5.1

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.14.3 soupsieve-2.8.3 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [22]:
df[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547

In [38]:
url="https://countrycode.org/"
pd.read_html(url,match="COUNTRY",header=0)[0]

,COUNTRY,COUNTRY CODE,ISO CODES,POPULATION,AREA KM2,GDP $USD
0,Afghanistan,93,AF / AFG,29121286,647500,20.65 Billion
1,Albania,355,AL / ALB,2986952,28748,12.8 Billion
2,Algeria,213,DZ / DZA,34586184,2381740,215.7 Billion
3,American Samoa,1-684,AS / ASM,57881,199,462.2 Million
4,Andorra,376,AD / AND,84000,468,4.8 Billion
...,...,...,...,...,...,...
235,Wallis and Futuna,681,WF / WLF,16025,274,NaN
236,Western Sahara,212,EH / ESH,273008,266000,NaN
237,Yemen,967,YE / YEM,23495361,527970,43.89 Billion
238,Zambia,260,ZM / ZMB,13460305,752614,22.24 Billion
239,Zimbabwe,263,ZW / ZWE,11651858,390580,10.48 Billion

In [23]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
df_excel=pd.read_excel('data.xlsx')
df_excel

   Name  Age
0  Anik   32
1  Jack   34
2  John   31

In [42]:
df_excel.to_pickle('df_excel')

In [43]:
pd.read_pickle('df_excel')

   Name  Age
0  Anik   32
1  Jack   34
2  John   31

In [53]:
#coping_data_to_clipboard
pd.read_clipboard()

Empty DataFrame
Columns: [#coping_data_to_clipboard]
Index: []

In [64]:
from urllib.request import Request, urlopen
from io import BytesIO

stata_url = 'https://www.stata-press.com/data/r16/breathe.dta'
req = Request(stata_url, headers={'User-Agent': 'curl/7.64.1'})
with urlopen(req) as resp:
    df_stata = pd.read_stata(BytesIO(resp.read()))

df_stata.head()

,react,correct,omissions,no2_class,no2_home,age,age0,sex,grade,overweight,...,msmoke,meducation,feducation,siblings_old,siblings_young,sev_home,green_home,noise_school,sev_school,precip
0,764.584000,125.0,2.0,16.087734,26.794014,10.340862,8.0,Female,4th,Normal weight,...,No smoking,Secondary,Secondary,1.0,0.0,0.838710,0.426315,35.200001,0.645161,0.3
1,855.818898,127.0,1.0,16.087734,33.398342,10.234086,3.0,Female,4th,Normal weight,...,No smoking,University,Secondary,0.0,1.0,0.290323,0.228674,35.200001,0.645161,0.3
2,932.983051,118.0,4.0,16.087734,29.154181,9.015742,3.0,Male,3rd,Normal weight,...,No smoking,University,University,0.0,1.0,0.612903,0.298590,35.200001,0.645161,0.3
3,506.440945,127.0,0.0,16.087734,25.067272,10.428473,3.0,Female,4th,Overweight,...,No smoking,University,Secondary,0.0,1.0,0.483871,0.360645,35.200001,0.645161,0.3
4,580.301587,126.0,0.0,16.087734,30.572056,9.330595,6.0,Male,3rd,Normal weight,...,No smoking,University,University,1.0,0.0,0.612903,0.239222,35.200001,0.645161,0.3